### ISSUE TITLE
Revert *.android.com

### ISSUE THREAD

**Issue by closure11** [eallion/uBlacklist-subscription-compilation#49]
<img width="356" alt="image" src="https://github.com/user-attachments/assets/8e198686-bd24-4d3d-861a-466b0c38183d">

**Comment by closure11** [comment]
And `*.microsoft.com`. The current rules seem very aggressive. Is there something wrong?

<img width="260" alt="image" src="https://github.com/user-attachments/assets/2a2c95c7-c7f2-4922-9c3a-92c25eca08de">

**Comment by chaoliu719** [comment]
It seems caused by commit [e20bb09](https://github.com/eallion/uBlacklist-subscription-compilation/commit/e20bb090c49b7eafa135c44e243696a6919cefac).

I have opened an [issue ](https://github.com/eallion/uBlacklist-subscription-compilation/issues/50) about this commit as it added a new personally subscription.
